version: "2.4"

services:
  mynginx:
    container_name: mynginx
    image: nginx:1.20-alpine
    networks:
      - myappli_net
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - myphp
  myphp:
    container_name: myphp
    image: myphp_mysql:7.4
    networks:
      - myappli_net
    volumes:
      - ./php/index.php:/srv/http/index.php
    depends_on:
      - mybdd
  mybdd:
    container_name: mybdd
    image: mariadb:10.5
    networks:
      - myappli_net
    volumes:
      - mybdd_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: roottoor

volumes:
  mybdd_vol:

networks:
  myappli_net: