version: "2.4"
services: 
  portainer: 
    container_name: portainer
    image: portainer/portainer-ce 
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock